import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, test } from "bun:test";
import { inspectRegisteredProject } from "./inspection";
import { mapDesignSystem } from "./mapping";
import { validateProposedFileChanges, projectFileHash } from "./proposal";
import { applyProjectFileChanges, rollbackProjectSnapshot, projectRootIdentity } from "./application";
import { createApprovalBinding, verifyApproval } from "./approval";
import { validateProject } from "./validation";

async function fixture(): Promise<string> { const root = await mkdtemp(join(tmpdir(), "designflow-stage4-")); await mkdir(join(root, "src/components"), { recursive: true }); await writeFile(join(root, "package.json"), JSON.stringify({ name: "fixture", dependencies: { react: "18.0.0" }, scripts: { typecheck: "bun --version", build: "bun --version" } })); await writeFile(join(root, "src/components/Button.tsx"), "export function Button(props: {label: string}) { return <button>{props.label}</button> }\n"); await writeFile(join(root, "src/tokens.css"), ":root { --color-brand: #123456; --space-md: 16px; }\n"); return root; }
const spec = { schemaVersion: "2", sourceIdentity: { designFile: "file" }, frames: ["Home"], hierarchy: [{ id: "node-1", name: "Button" }], designTokens: { colors: ["color-brand"], spacing: [], typography: [], radii: [], borders: [], shadows: [], referencedVariableNames: [] }, components: [{ name: "Button", role: "button", sourceNodeIds: ["node-1"], variants: [], requiredAssets: [], implementationNotes: [] }], layoutBehavior: [], responsiveAssumptions: [], assets: [], content: [], interactions: [], states: [], accessibilityNotes: ["name button"], ambiguities: [], agentVersion: "1" };

describe("Stage 4 implementation capability", () => {
  test("inspects a registered project deterministically and excludes secrets", async () => { const root = await fixture(); await writeFile(join(root, ".env"), "TOKEN=secret\n"); const project = inspectRegisteredProject({ id: "p1", name: "Fixture", rootPath: root }); expect(project.project.id).toBe("p1"); expect(project.runtime.framework).toBe("react"); expect(project.designSystem.tokens.map((token) => token.reference)).toContain("var(--color-brand)"); await rm(root, { recursive: true, force: true }); });
  test("maps exact components and tokens, with no fabricated reuse", async () => { const root = await fixture(); const context = inspectRegisteredProject({ id: "p1", name: "Fixture", rootPath: root }); const mapping = mapDesignSystem(spec, context); expect(mapping.componentMappings[0]?.action).toBe("reuse"); expect(mapping.tokenMappings[0]?.action).toBe("reuse"); await rm(root, { recursive: true, force: true }); });
  test("rejects traversal and modifications without a base hash", async () => { const root = await fixture(); expect(() => validateProposedFileChanges({ schemaVersion: "1", projectId: "p1", baseProjectFingerprint: "fp", files: [{ path: "../escape.ts", action: "create", content: "x", reason: "bad", relatedDesignNodeIds: [] }], packageChanges: [], commandsRequested: [], assumptions: [], unresolvedItems: [] }, root)).toThrow(); expect(() => validateProposedFileChanges({ schemaVersion: "1", projectId: "p1", baseProjectFingerprint: "fp", files: [{ path: "src/x.ts", action: "modify", content: "x", reason: "bad", relatedDesignNodeIds: [] }], packageChanges: [], commandsRequested: [], assumptions: [], unresolvedItems: [] }, root)).toThrow(); await rm(root, { recursive: true, force: true }); });
  test("applies approved changes, snapshots them, and rolls back", async () => { const root = await fixture(); const state = await mkdtemp(join(tmpdir(), "designflow-state-")); const proposal = { schemaVersion: "1" as const, projectId: "p1", baseProjectFingerprint: "fp", files: [{ path: "src/New.ts", action: "create" as const, content: "export const value = 1;\n", reason: "test", relatedDesignNodeIds: [] }], packageChanges: [], commandsRequested: [], assumptions: [], unresolvedItems: [] }; const result = await applyProjectFileChanges("p1", root, proposal, projectRootIdentity(root), state); expect(await readFile(join(root, "src/New.ts"), "utf8")).toContain("value"); await rollbackProjectSnapshot(root, result.snapshot); await expect(readFile(join(root, "src/New.ts"))).rejects.toBeDefined(); await rm(root, { recursive: true, force: true }); await rm(state, { recursive: true, force: true }); });
  test("restores a modified file during rollback", async () => { const root = await fixture(); const state = await mkdtemp(join(tmpdir(), "designflow-state-")); const original = await readFile(join(root, "src/components/Button.tsx"), "utf8"); const proposal = { schemaVersion: "1" as const, projectId: "p1", baseProjectFingerprint: "fp", files: [{ path: "src/components/Button.tsx", action: "modify" as const, content: "export function Button() { return <button>changed</button>; }\n", expectedBaseHash: projectFileHash(join(root, "src/components/Button.tsx")), reason: "test", relatedDesignNodeIds: [] }], packageChanges: [], commandsRequested: [], assumptions: [], unresolvedItems: [] }; const result = await applyProjectFileChanges("p1", root, proposal, projectRootIdentity(root), state); expect(await readFile(join(root, "src/components/Button.tsx"), "utf8")).toContain("changed"); await rollbackProjectSnapshot(root, result.snapshot); expect(await readFile(join(root, "src/components/Button.tsx"), "utf8")).toBe(original); await rm(root, { recursive: true, force: true }); await rm(state, { recursive: true, force: true }); });
  test("binds approval to proposal and project fingerprint", () => { const proposal = { schemaVersion: "1" as const, projectId: "p1", baseProjectFingerprint: "fp", files: [], packageChanges: [], commandsRequested: [], assumptions: [], unresolvedItems: [] }; const binding = createApprovalBinding("proposal-1", proposal, new Date("2026-01-01T00:00:00Z")); expect(() => verifyApproval({ ...binding, status: "approved" }, "proposal-1", proposal, "changed")).toThrow(); });
  test("enforces inspection limits and skips symlink escapes", async () => { const root = await fixture(); const outside = await mkdtemp(join(tmpdir(), "designflow-outside-")); await writeFile(join(outside, "secret.ts"), "export const secret = true"); await symlink(outside, join(root, "src/outside")); const limited = inspectRegisteredProject({ id: "p1", name: "Fixture", rootPath: root }, { maxFiles: 1 }); const safe = inspectRegisteredProject({ id: "p1", name: "Fixture", rootPath: root }); expect(limited.warnings.some((warning) => warning.code === "FILE_COUNT_LIMIT")).toBe(true); expect(safe.warnings.some((warning) => warning.code === "SYMLINK_SKIPPED")).toBe(true); await rm(root, { recursive: true, force: true }); await rm(outside, { recursive: true, force: true }); });
  test("changes fingerprint only after source mutation", async () => { const root = await fixture(); const first = inspectRegisteredProject({ id: "p1", name: "Fixture", rootPath: root }); const second = inspectRegisteredProject({ id: "p1", name: "Fixture", rootPath: root }); expect(second.project.contextFingerprint).toBe(first.project.contextFingerprint); await writeFile(join(root, "src/App.tsx"), "export const App = () => null;\n"); const third = inspectRegisteredProject({ id: "p1", name: "Fixture", rootPath: root }); expect(third.project.contextFingerprint).not.toBe(first.project.contextFingerprint); await rm(root, { recursive: true, force: true }); });
  test("fails rollback when an applied file was externally modified", async () => { const root = await fixture(); const state = await mkdtemp(join(tmpdir(), "designflow-state-")); const proposal = { schemaVersion: "1" as const, projectId: "p1", baseProjectFingerprint: "fp", files: [{ path: "src/New.ts", action: "create" as const, content: "export const value = 1;\n", reason: "test", relatedDesignNodeIds: [] }], packageChanges: [], commandsRequested: [], assumptions: [], unresolvedItems: [] }; const result = await applyProjectFileChanges("p1", root, proposal, projectRootIdentity(root), state); await writeFile(join(root, "src/New.ts"), "external mutation\n"); await expect(rollbackProjectSnapshot(root, result.snapshot)).rejects.toThrow(); expect(projectFileHash(join(root, "src/New.ts"))).toBeDefined(); await rm(root, { recursive: true, force: true }); await rm(state, { recursive: true, force: true }); });
  test("rejects unsupported and private targets", async () => { const root = await fixture(); const base = { schemaVersion: "1" as const, projectId: "p1", baseProjectFingerprint: "fp", packageChanges: [], commandsRequested: [], assumptions: [], unresolvedItems: [] }; expect(() => validateProposedFileChanges({ ...base, files: [{ path: "src/run.sh", action: "create", content: "echo unsafe", reason: "bad", relatedDesignNodeIds: [] }] }, root)).toThrow(); expect(() => validateProposedFileChanges({ ...base, files: [{ path: ".env", action: "create", content: "secret", reason: "bad", relatedDesignNodeIds: [] }] }, root)).toThrow(); await rm(root, { recursive: true, force: true }); });
  test("marks missing checks unavailable and never runs model-requested commands", async () => { const root = await fixture(); const context = inspectRegisteredProject({ id: "p1", name: "Fixture", rootPath: root }); const checks = await validateProject({ ...context, commands: { ...context.commands, lint: undefined, test: undefined } }, root); expect(checks.find((check) => check.name === "lint")?.status).toBe("unavailable"); expect(checks.find((check) => check.name === "build")?.status).toBe("passed"); await rm(root, { recursive: true, force: true }); });
});
