export { ImplementationError } from "./errors";
export { inspectRegisteredProject } from "./inspection";
export type { InspectionLimits } from "./inspection";
export { mapDesignSystem } from "./mapping";
export { validateProposedFileChanges, projectFileHash } from "./proposal";
export { createApprovalBinding, verifyApproval, proposalHash } from "./approval";
export { applyProjectFileChanges, createProjectSnapshot, rollbackProjectSnapshot, projectRootIdentity } from "./application";
export { assertGitSafeForWrite, inspectGitSafety, type GitSafetyReport } from "./git-safety";
export { acquireProjectWriteLock, type ProjectWriteLock, type ProjectWriteLockRecord } from "./project-write-lock";
export type { SnapshotEntry, ProjectSnapshot, ApplicationResult } from "./application";
export { validateProject, makeValidationReport } from "./validation";
export { validateProposedModules, changedExecutableFiles, isExecutableSourcePath, PROPOSED_STATE_ENTRY_FILE } from "./proposed-state-validation";
export type { ProposedModuleValidationResult, ProposedModuleValidationOptions, ProposedModuleDiagnostic } from "./proposed-state-validation";
export type { ValidationOptions } from "./validation";
export { applyAndValidateProject } from "./run";
