export { ImplementationError } from "./errors";
export { inspectRegisteredProject } from "./project-inspection/inspection";
export type { InspectionLimits } from "./project-inspection/inspection";
export { mapDesignSystem } from "./project-inspection/design-system-mapping";
export { validateProposedFileChanges, projectFileHash } from "./proposal/proposal";
export { createApprovalBinding, verifyApproval, proposalHash } from "./approval/approval";
export { applyProjectFileChanges, createProjectSnapshot, rollbackProjectSnapshot, projectRootIdentity } from "./project-mutation/application";
export { assertGitSafeForWrite, inspectGitSafety, type GitSafetyReport } from "./project-mutation/git-safety";
export { acquireProjectWriteLock, type ProjectWriteLock, type ProjectWriteLockRecord } from "./project-mutation/project-write-lock";
export type { SnapshotEntry, ProjectSnapshot, ApplicationResult } from "./project-mutation/application";
export { validateProject, makeValidationReport } from "./validation/validation";
export { deriveImplementationCoveragePlan, validateImplementationCoverage } from "./proposal/coverage";
export type { CoverageValidationResult } from "./proposal/coverage";
export { validateProposedModules, changedExecutableFiles, isExecutableSourcePath, PROPOSED_STATE_ENTRY_FILE } from "./proposal/proposed-state-validation";
export type { ProposedModuleValidationResult, ProposedModuleValidationOptions, ProposedModuleDiagnostic } from "./proposal/proposed-state-validation";
export type { ValidationOptions } from "./validation/validation";
export { applyAndValidateProject } from "./run";
