import { spawn } from "node:child_process";
import { implementationValidationReportSchema, projectImplementationContextV1Schema, type ImplementationValidationReport } from "@designflow/sdk";
import { ImplementationError } from "./errors";

export interface ValidationOptions { timeoutMs?: number; maxOutputBytes?: number; signal?: AbortSignal; }
const redact = (value: string) => value.replace(/([A-Za-z0-9_-]*(?:token|secret|password|credential)[A-Za-z0-9_-]*\s*[=:]\s*)[^\s\n]+/gi, "$1[REDACTED]");
async function run(executable: string, args: string[], cwd: string, options: ValidationOptions): Promise<{code:number; output:string; duration:number}> { return await new Promise((resolve, reject) => { const started = Date.now(); const child = spawn(executable, args, { cwd, shell: false, stdio: ["ignore", "pipe", "pipe"] }); let output = ""; const limit = options.maxOutputBytes ?? 100_000; const append = (chunk: Buffer) => { output += chunk.toString(); if (Buffer.byteLength(output) > limit) { child.kill(); reject(new ImplementationError("ERR_VALIDATION_OUTPUT_TOO_LARGE", "Validation output exceeded the configured limit.")); } }; child.stdout.on("data", append); child.stderr.on("data", append); const timer = setTimeout(() => { child.kill(); reject(new ImplementationError("ERR_VALIDATION_TIMEOUT", "Project validation timed out.")); }, options.timeoutMs ?? 120_000); options.signal?.addEventListener("abort", () => { child.kill(); reject(new ImplementationError("ERR_VALIDATION_ABORTED", "Project validation was cancelled.")); }, { once: true }); child.on("error", reject); child.on("close", (code) => { clearTimeout(timer); resolve({ code: code ?? 1, output: redact(output), duration: Date.now() - started }); }); }); }
export async function validateProject(rawContext: unknown, root: string, options: ValidationOptions = {}): Promise<ImplementationValidationReport["checks"]> {
  const context = projectImplementationContextV1Schema.parse(rawContext);
  const checks: ImplementationValidationReport["checks"] = []; const commands = [context.commands.format, context.commands.typecheck, context.commands.lint, context.commands.build, context.commands.test];
  for (const [index, command] of commands.entries()) { if (!command) { const name = (["format", "typecheck", "lint", "build", "test"] as const)[index]!; checks.push({ name, status: "unavailable", required: false, summary: "No safe project-declared command was found." }); continue; } try { const result = await run(command.executable, command.args, root, options); checks.push({ name: command.name, status: result.code === 0 ? "passed" : "failed", required: command.required, commandReference: [command.executable, ...command.args].join(" "), exitCode: result.code, durationMs: result.duration, summary: result.code === 0 ? "Command completed successfully." : redact(result.output.slice(-2_000)) || "Command failed." }); } catch (error) { if (error instanceof ImplementationError) throw error; checks.push({ name: command.name, status: "failed", required: command.required, commandReference: [command.executable, ...command.args].join(" "), summary: "Command could not be started." }); } }
  return checks;
}
export function makeValidationReport(input: Omit<ImplementationValidationReport, "schemaVersion">): ImplementationValidationReport { return implementationValidationReportSchema.parse({ schemaVersion: "1", ...input }); }
