// packages/agents/src/catalog/specification-evidence-bundle.ts
//
// DF-SPEC-05: the deterministic evidence compiler that sits between the rich
// persisted `FigmaSourceSnapshot` and the Specification AI.
//
//   rich FigmaSourceSnapshot  →  compiler (this file)  →  evidence bundle
//                                                       →  Specification AI
//
// DF-SPEC-04 made the snapshot rich: instance descendants, exact copy,
// component identity, variants, slots and styles all survive retrieval. That
// snapshot is the persisted source of truth and does not change. What changes
// here is only what the *model* is handed: serializing the raw snapshot sent
// the same shared component styling once per instance, an empty `fills` /
// `strokes` / `effects` / `exportSettings` / `interactions` / `properties`
// bag on every node, and transport bookkeeping the specification cannot use.
//
// The compiler is deterministic and lossless for implementation-relevant
// facts: every element, instance and asset keeps its Figma node id, so every
// statement in the produced specification remains traceable to evidence, and
// the agent's node-id fabrication check still validates against the snapshot.
// Nothing here is generated by a model, and nothing is inferred — a fact that
// is not in the snapshot is not in the bundle.
import type {
  FigmaAssetSnapshot,
  FigmaNodeSnapshot,
  FigmaSourceSnapshot,
} from "@designflow/sdk";

export interface EvidenceStyle {
  readonly background?: string;
  readonly border?: string;
  readonly radius?: string;
  readonly opacity?: number;
  readonly effects?: readonly string[];
}

export interface EvidenceElement {
  readonly nodeId: string;
  readonly name: string;
  readonly type: string;
  readonly parentId?: string;
  /** Position among its parent's children — the visual/DOM order. */
  readonly order: number;
  /** `"392x56"` when evidenced. */
  readonly size?: string;
  /** e.g. `"vertical gap 16 padding 16/24/16/24"`. */
  readonly layout?: string;
  readonly text?: string;
  /** e.g. `"Poppins Medium 20px"`. */
  readonly typography?: string;
  readonly textColor?: string;
  readonly style?: EvidenceStyle;
  /** Set when this element is a component instance; see `instances`. */
  readonly instanceOf?: string;
  readonly interactions?: readonly string[];
}

export interface EvidenceComponentSlot {
  readonly nodeId: string;
  readonly name: string;
  readonly type: string;
  readonly depth: number;
  readonly text?: string;
  readonly size?: string;
  readonly typography?: string;
  readonly textColor?: string;
  readonly style?: EvidenceStyle;
}

export interface EvidenceComponent {
  /** The reference used by elements/instances — the component's name. */
  readonly ref: string;
  readonly name: string;
  readonly componentIds: readonly string[];
  /** Property/variant names observed across the instances of this component. */
  readonly propertyNames?: readonly string[];
  /** Style facts identical across every observed instance (sent once). */
  readonly sharedStyle?: EvidenceStyle;
  readonly sharedSize?: string;
  readonly sharedLayout?: string;
  /** Descendant anatomy shared by every instance: names/types, no content. */
  readonly anatomy: readonly { name: string; type: string; depth: number }[];
  readonly instanceCount: number;
}

export interface EvidenceInstance {
  readonly nodeId: string;
  readonly name: string;
  readonly componentRef: string;
  readonly parentId?: string;
  /** Real Figma component property values (`{ variant: "Expenses" }`). */
  readonly propertyValues?: Readonly<Record<string, string>>;
  /** This instance's own descendants — exact copy, icons and slots. */
  readonly contents: readonly EvidenceComponentSlot[];
  /** Only what differs from the component's shared facts. */
  readonly size?: string;
  readonly layout?: string;
  readonly style?: EvidenceStyle;
}

export interface EvidenceFoundations {
  readonly colors: readonly string[];
  readonly typography: readonly string[];
  readonly spacing: readonly string[];
  readonly radii: readonly string[];
  readonly borders: readonly string[];
  readonly effects: readonly string[];
  readonly variables: readonly { name: string; value: string; type?: string }[];
}

export interface EvidenceBundleMetrics {
  readonly snapshotNodeCount: number;
  readonly snapshotBytes: number;
  readonly bundleElementCount: number;
  readonly bundleComponentCount: number;
  readonly bundleInstanceCount: number;
  readonly bundleBytes: number;
  /** Whole-percent reduction of serialized model input, never negative. */
  readonly reductionPercent: number;
}

export interface SpecificationEvidenceBundle {
  readonly schemaVersion: "1";
  readonly source: {
    readonly designFile: string;
    readonly fileKey?: string;
    readonly documentVersion?: string;
    readonly frames: readonly string[];
    readonly rootNodeIds: readonly string[];
  };
  readonly screen?: {
    readonly nodeId: string;
    readonly name: string;
    readonly size?: string;
    readonly layout?: string;
    readonly background?: string;
  };
  readonly elements: readonly EvidenceElement[];
  readonly components: readonly EvidenceComponent[];
  readonly instances: readonly EvidenceInstance[];
  readonly foundations: EvidenceFoundations;
  readonly assets: readonly { id: string; name: string; type: string; reference?: string }[];
  readonly interactions: readonly { nodeId: string; description: string }[];
  /** Retrieval facts the specification must reason about (bounded). */
  readonly notes: readonly string[];
  readonly capabilities: FigmaSourceSnapshot["capabilities"];
  readonly metrics: EvidenceBundleMetrics;
}

// ── Fact extraction (deterministic, evidence-only) ───────────────

function solidColor(paint: Record<string, unknown>): string | undefined {
  const direct = paint["color"];
  if (typeof direct === "string") return direct.toUpperCase();
  if (typeof direct !== "object" || direct === null) return undefined;
  const { r, g, b } = direct as { r?: unknown; g?: unknown; b?: unknown };
  if (typeof r !== "number" || typeof g !== "number" || typeof b !== "number") return undefined;
  const hex = (channel: number): string => Math.round(channel * 255).toString(16).padStart(2, "0");
  return `#${hex(r)}${hex(g)}${hex(b)}`.toUpperCase();
}

function firstColor(paints: readonly Record<string, unknown>[]): string | undefined {
  for (const paint of paints) {
    const color = solidColor(paint);
    if (color !== undefined) return color;
  }
  return undefined;
}

function effectStrings(node: FigmaNodeSnapshot): string[] {
  return node.effects
    .map((effect) => {
      const type = typeof effect["type"] === "string" ? (effect["type"] as string) : undefined;
      if (type === undefined) return undefined;
      const radius = typeof effect["radius"] === "number" ? ` ${effect["radius"] as number}px` : "";
      const color = solidColor(effect);
      return `${type}${radius}${color !== undefined ? ` ${color}` : ""}`;
    })
    .filter((value): value is string => value !== undefined);
}

function sizeOf(node: FigmaNodeSnapshot): string | undefined {
  const box = node.absoluteBoundingBox ?? node.relativeBoundingBox;
  if (box !== undefined) return `${round(box.width)}x${round(box.height)}`;
  const properties = node.properties as Record<string, unknown>;
  const width = properties["widthPx"];
  const height = properties["heightPx"];
  if (typeof width === "number" && typeof height === "number") return `${round(width)}x${round(height)}`;
  return undefined;
}

function round(value: number): number {
  return Math.round(value * 100) / 100;
}

function layoutOf(node: FigmaNodeSnapshot): string | undefined {
  const parts: string[] = [];
  if (node.layoutMode !== undefined && node.layoutMode !== "NONE") {
    parts.push(node.layoutMode === "HORIZONTAL" ? "horizontal" : "vertical");
  }
  if (node.itemSpacing !== undefined) parts.push(`gap ${round(node.itemSpacing)}`);
  if (node.padding !== undefined) {
    const { top, right, bottom, left } = node.padding;
    parts.push(`padding ${round(top)}/${round(right)}/${round(bottom)}/${round(left)}`);
  } else {
    const properties = node.properties as Record<string, unknown>;
    const paddingX = properties["paddingXPx"];
    const paddingY = properties["paddingYPx"];
    if (typeof paddingX === "number" || typeof paddingY === "number") {
      parts.push(`padding ${typeof paddingY === "number" ? round(paddingY) : 0}/${typeof paddingX === "number" ? round(paddingX) : 0}`);
    }
  }
  if (node.primaryAxisAlignItems !== undefined) parts.push(`main ${node.primaryAxisAlignItems.toLowerCase()}`);
  if (node.counterAxisAlignItems !== undefined) parts.push(`cross ${node.counterAxisAlignItems.toLowerCase()}`);
  if (node.sizingHorizontal !== undefined || node.sizingVertical !== undefined) {
    parts.push(`sizing ${node.sizingHorizontal ?? "-"}/${node.sizingVertical ?? "-"}`);
  }
  return parts.length > 0 ? parts.join(" ") : undefined;
}

function typographyOf(node: FigmaNodeSnapshot): string | undefined {
  const typography = (node.properties as Record<string, unknown>)["typography"];
  if (typeof typography !== "object" || typography === null) return undefined;
  const { fontFamily, fontStyle, fontSize } = typography as {
    fontFamily?: unknown;
    fontStyle?: unknown;
    fontSize?: unknown;
  };
  const parts = [
    typeof fontFamily === "string" ? fontFamily : undefined,
    typeof fontStyle === "string" ? fontStyle : undefined,
    typeof fontSize === "number" ? `${round(fontSize)}px` : undefined,
  ].filter((part): part is string => part !== undefined);
  return parts.length > 0 ? parts.join(" ") : undefined;
}

function styleOf(node: FigmaNodeSnapshot): EvidenceStyle | undefined {
  const style: {
    background?: string;
    border?: string;
    radius?: string;
    opacity?: number;
    effects?: string[];
  } = {};
  const background = firstColor(node.fills);
  const isText = node.type === "TEXT";
  if (background !== undefined && !isText) style.background = background;
  const border = firstColor(node.strokes);
  if (border !== undefined) style.border = border;
  if (node.cornerRadius !== undefined) style.radius = `${round(node.cornerRadius)}px`;
  if (node.opacity !== undefined && node.opacity !== 1) style.opacity = node.opacity;
  const effects = effectStrings(node);
  if (effects.length > 0) style.effects = effects;
  return Object.keys(style).length > 0 ? style : undefined;
}

function textColorOf(node: FigmaNodeSnapshot): string | undefined {
  return node.type === "TEXT" ? firstColor(node.fills) : undefined;
}

function interactionsOf(node: FigmaNodeSnapshot): string[] {
  return node.interactions
    .map((interaction) => {
      const trigger = interaction["trigger"];
      const action = interaction["action"] ?? interaction["type"];
      const triggerText =
        typeof trigger === "object" && trigger !== null
          ? String((trigger as Record<string, unknown>)["type"] ?? "")
          : typeof trigger === "string"
            ? trigger
            : "";
      const actionText =
        typeof action === "object" && action !== null
          ? String((action as Record<string, unknown>)["type"] ?? "")
          : typeof action === "string"
            ? action
            : "";
      const combined = [triggerText, actionText].filter((part) => part.length > 0).join(" → ");
      return combined.length > 0 ? combined : undefined;
    })
    .filter((value): value is string => value !== undefined);
}

// ── Compilation ──────────────────────────────────────────────────

function withOptional<T>(base: T, extra: Record<string, unknown>): T {
  const result: Record<string, unknown> = { ...(base as Record<string, unknown>) };
  for (const [key, value] of Object.entries(extra)) {
    if (value !== undefined) result[key] = value;
  }
  return result as T;
}

function sameStyle(left: EvidenceStyle | undefined, right: EvidenceStyle | undefined): boolean {
  return JSON.stringify(left ?? null) === JSON.stringify(right ?? null);
}

/**
 * Compiles the rich snapshot into the compact, deterministic representation
 * the Specification AI reasons over. Sparse snapshots compile to small
 * truthful bundles: nothing is required, and nothing absent is invented.
 */
export function compileSpecificationEvidenceBundle(
  snapshot: FigmaSourceSnapshot,
): SpecificationEvidenceBundle {
  const byId = new Map(snapshot.nodes.map((node) => [node.id, node]));
  const componentById = new Map(snapshot.components.map((component) => [component.id, component]));

  const isInstance = (node: FigmaNodeSnapshot): boolean =>
    node.type === "INSTANCE" || componentById.has(node.id);

  // Every node that lives inside a component instance is carried by that
  // instance rather than repeated in the flat element list.
  const insideInstance = new Set<string>();
  const markDescendants = (node: FigmaNodeSnapshot): void => {
    for (const childId of node.childIds) {
      const child = byId.get(childId);
      if (child === undefined || insideInstance.has(childId)) continue;
      insideInstance.add(childId);
      markDescendants(child);
    }
  };
  for (const node of snapshot.nodes) {
    if (isInstance(node)) markDescendants(node);
  }

  const orderOf = (node: FigmaNodeSnapshot): number => {
    const parent = node.parentId !== undefined ? byId.get(node.parentId) : undefined;
    const index = parent?.childIds.indexOf(node.id) ?? -1;
    return index >= 0 ? index : 0;
  };

  const root = snapshot.nodes.find((node) => node.parentId === undefined) ?? snapshot.nodes[0];

  const componentRefOf = (node: FigmaNodeSnapshot): string =>
    componentById.get(node.id)?.name ?? node.name;

  const elements: EvidenceElement[] = snapshot.nodes
    .filter((node) => !insideInstance.has(node.id))
    .map((node) =>
      withOptional<EvidenceElement>(
        {
          nodeId: node.id,
          name: node.name,
          type: node.type,
          order: orderOf(node),
        },
        {
          parentId: node.parentId,
          size: sizeOf(node),
          layout: layoutOf(node),
          text: node.characters,
          typography: typographyOf(node),
          textColor: textColorOf(node),
          style: styleOf(node),
          instanceOf: isInstance(node) ? componentRefOf(node) : undefined,
          interactions: interactionsOf(node).length > 0 ? interactionsOf(node) : undefined,
        },
      ),
    );

  // Instances: each keeps its own descendants (exact copy, icon slots) and
  // only the style facts that differ from its component's shared facts.
  const instanceNodes = snapshot.nodes.filter((node) => isInstance(node) && !insideInstance.has(node.id));

  const contentsOf = (node: FigmaNodeSnapshot): EvidenceComponentSlot[] => {
    const slots: EvidenceComponentSlot[] = [];
    const walk = (current: FigmaNodeSnapshot, depth: number): void => {
      for (const childId of current.childIds) {
        const child = byId.get(childId);
        if (child === undefined) continue;
        slots.push(
          withOptional<EvidenceComponentSlot>(
            { nodeId: child.id, name: child.name, type: child.type, depth },
            {
              text: child.characters,
              size: sizeOf(child),
              typography: typographyOf(child),
              textColor: textColorOf(child),
              style: styleOf(child),
            },
          ),
        );
        walk(child, depth + 1);
      }
    };
    walk(node, 0);
    return slots;
  };

  const groups = new Map<string, FigmaNodeSnapshot[]>();
  for (const node of instanceNodes) {
    const ref = componentRefOf(node);
    groups.set(ref, [...(groups.get(ref) ?? []), node]);
  }

  const components: EvidenceComponent[] = [...groups.entries()].map(([ref, members]) => {
    const first = members[0]!;
    const firstStyle = styleOf(first);
    const firstSize = sizeOf(first);
    const firstLayout = layoutOf(first);
    const shared = {
      style: members.every((member) => sameStyle(styleOf(member), firstStyle)) ? firstStyle : undefined,
      size: members.every((member) => sizeOf(member) === firstSize) ? firstSize : undefined,
      layout: members.every((member) => layoutOf(member) === firstLayout) ? firstLayout : undefined,
    };
    const propertyNames = [
      ...new Set(members.flatMap((member) => Object.keys(member.variantProperties ?? {}))),
    ];
    return withOptional<EvidenceComponent>(
      {
        ref,
        name: componentById.get(first.id)?.name ?? ref,
        componentIds: members.map((member) => member.id),
        anatomy: contentsOf(first).map((slot) => ({ name: slot.name, type: slot.type, depth: slot.depth })),
        instanceCount: members.length,
      },
      {
        propertyNames: propertyNames.length > 0 ? propertyNames : undefined,
        sharedStyle: shared.style,
        sharedSize: shared.size,
        sharedLayout: shared.layout,
      },
    );
  });

  const sharedByRef = new Map(components.map((component) => [component.ref, component]));

  const instances: EvidenceInstance[] = instanceNodes.map((node) => {
    const ref = componentRefOf(node);
    const shared = sharedByRef.get(ref);
    const style = styleOf(node);
    const size = sizeOf(node);
    const layout = layoutOf(node);
    return withOptional<EvidenceInstance>(
      {
        nodeId: node.id,
        name: node.name,
        componentRef: ref,
        contents: contentsOf(node),
      },
      {
        parentId: node.parentId,
        propertyValues: node.variantProperties,
        style: sameStyle(style, shared?.sharedStyle) ? undefined : style,
        size: size === shared?.sharedSize ? undefined : size,
        layout: layout === shared?.sharedLayout ? undefined : layout,
      },
    );
  });

  // Foundations: every repeated raw value collapses to one occurrence.
  const unique = (values: readonly (string | undefined)[]): string[] =>
    [...new Set(values.filter((value): value is string => value !== undefined))].sort();

  const foundations: EvidenceFoundations = {
    colors: unique([
      ...snapshot.nodes.map((node) => firstColor(node.fills)),
      ...snapshot.nodes.map((node) => firstColor(node.strokes)),
    ]),
    typography: unique(snapshot.nodes.map(typographyOf)),
    spacing: unique(
      snapshot.nodes.flatMap((node) => [
        node.itemSpacing !== undefined ? `${round(node.itemSpacing)}px` : undefined,
        node.padding !== undefined
          ? `padding ${round(node.padding.top)}/${round(node.padding.right)}/${round(node.padding.bottom)}/${round(node.padding.left)}`
          : undefined,
      ]),
    ),
    radii: unique(snapshot.nodes.map((node) => (node.cornerRadius !== undefined ? `${round(node.cornerRadius)}px` : undefined))),
    borders: unique(snapshot.nodes.map((node) => firstColor(node.strokes))),
    effects: unique(snapshot.nodes.flatMap(effectStrings)),
    variables: snapshot.variables.map((variable) =>
      withOptional<{ name: string; value: string; type?: string }>(
        { name: variable.name, value: typeof variable.value === "string" ? variable.value : JSON.stringify(variable.value) },
        { type: variable.type },
      ),
    ),
  };

  const assets = snapshot.assets.map((asset: FigmaAssetSnapshot) =>
    withOptional<{ id: string; name: string; type: string; reference?: string }>(
      { id: asset.id, name: asset.name, type: asset.type },
      { reference: asset.reference },
    ),
  );

  const interactions = snapshot.nodes.flatMap((node) =>
    interactionsOf(node).map((description) => ({ nodeId: node.id, description })),
  );

  const notes = snapshot.warnings
    // Transport bookkeeping the specification cannot act on is dropped; a
    // bounded-expansion or unsupported-evidence warning changes what the
    // specification may legitimately claim, so it is kept.
    .filter((warning) => /BOUNDED|UNSUPPORTED|UNAVAILABLE|TRUNCAT|PARTIAL/i.test(warning.code))
    .slice(0, 10)
    .map((warning) => `${warning.code}: ${warning.message}`);

  const screen =
    root === undefined
      ? undefined
      : withOptional<NonNullable<SpecificationEvidenceBundle["screen"]>>(
          { nodeId: root.id, name: root.name },
          {
            size: sizeOf(root),
            layout: layoutOf(root),
            background: firstColor(root.fills),
          },
        );

  const bundle = {
    schemaVersion: "1" as const,
    source: withOptional<SpecificationEvidenceBundle["source"]>(
      {
        designFile: snapshot.source.designFile,
        frames: snapshot.source.frames.length > 0
          ? snapshot.source.frames
          : snapshot.source.resolvedFrames.map((frame) => frame.name),
        rootNodeIds: snapshot.source.resolvedFrames.map((frame) => frame.id),
      },
      { fileKey: snapshot.source.fileKey, documentVersion: snapshot.source.documentVersion },
    ),
    ...(screen !== undefined ? { screen } : {}),
    elements,
    components,
    instances,
    foundations,
    assets,
    interactions,
    notes,
    capabilities: snapshot.capabilities,
  };

  const snapshotBytes = byteLength(JSON.stringify(snapshot));
  const bundleBytes = byteLength(JSON.stringify(bundle));

  return {
    ...bundle,
    metrics: {
      snapshotNodeCount: snapshot.nodes.length,
      snapshotBytes,
      bundleElementCount: elements.length,
      bundleComponentCount: components.length,
      bundleInstanceCount: instances.length,
      bundleBytes,
      reductionPercent:
        snapshotBytes > 0 ? Math.max(0, Math.round(((snapshotBytes - bundleBytes) / snapshotBytes) * 100)) : 0,
    },
  };
}

function byteLength(value: string): number {
  return new TextEncoder().encode(value).length;
}

/** Bytes ÷ 4 — the same coarse rule the model layer's budgeting uses. */
export function estimateTokens(bytes: number): number {
  return Math.ceil(bytes / 4);
}
