import { z } from "zod";
import { DesignFlowError, implementationApprovalBindingSchema, implementationValidationReportSchema, proposedFileChangesSchema, type Capability } from "@designflow/sdk";
import { applyProjectFileChanges, createApprovalBinding, createProjectSnapshot, inspectRegisteredProject, proposalHash, rollbackProjectSnapshot, validateProposedFileChanges, validateProject, type ProjectSnapshot } from "@designflow/capability-implementation";
import { readArtifact, writeArtifact } from "./artifact-io";
import { capabilityOutputSchema, type CapabilityOutput } from "./types";
import { IMPLEMENTATION_ARTIFACT_IDS, IMPLEMENTATION_ARTIFACT_TYPES, implementationWorkflowInputSchema, projectImplementationContextV1Schema } from "./implementation-types";

const inputSchema = implementationWorkflowInputSchema;
const projectInput = (input: unknown) => inputSchema.parse(input);

export const storeImplementationApprovalCapability: Capability<unknown, CapabilityOutput> = { id: "request-implementation-approval", name: "Request implementation approval", description: "Binds approval to the exact project and proposed changes", type: "human_gate", version: "1", inputSchema: z.unknown(), outputSchema: capabilityOutputSchema, async execute(context) { const proposal = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.proposal, proposedFileChangesSchema); const binding = createApprovalBinding(IMPLEMENTATION_ARTIFACT_IDS.proposal, proposal); return writeArtifact(context, { artifactId: IMPLEMENTATION_ARTIFACT_IDS.approval, artifactType: IMPLEMENTATION_ARTIFACT_TYPES.approval, name: "Implementation approval binding", payload: binding, summary: { projectId: binding.projectId, proposalHash: binding.proposalHash } }); } };

export const createProjectSnapshotCapability: Capability<unknown, CapabilityOutput> = { id: "create-project-snapshot", name: "Create project snapshot", description: "Creates a DesignFlow-controlled pre-write snapshot after approval", type: "write_fs", version: "1", inputSchema: inputSchema, outputSchema: capabilityOutputSchema, async execute(context, input) { const requested = projectInput(input); const project = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.projectContext, projectImplementationContextV1Schema); const proposal = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.proposal, proposedFileChangesSchema); const current = inspectRegisteredProject(requested.project); if (current.project.contextFingerprint !== proposal.baseProjectFingerprint) throw new Error("The project changed after the proposal was created. Generate a new proposal before continuing."); const snapshot = await createProjectSnapshot(project.project.id, requested.project.rootPath, validateProposedFileChanges(proposal, requested.project.rootPath), project.project.rootIdentity, requested.stateDirectory); return writeArtifact(context, { artifactId: IMPLEMENTATION_ARTIFACT_IDS.snapshot, artifactType: IMPLEMENTATION_ARTIFACT_TYPES.snapshot, name: "Project snapshot", payload: snapshot, summary: { runId: snapshot.runId, projectId: snapshot.projectId, fileCount: snapshot.entries.length } }); } };

export const applyApprovedFileChangesCapability: Capability<unknown, CapabilityOutput> = { id: "apply-approved-file-changes", name: "Apply approved file changes", description: "Applies only validated approved changes through the scoped filesystem service", type: "write_fs", version: "1", inputSchema: inputSchema, outputSchema: capabilityOutputSchema, async execute(context, input) { const requested = projectInput(input); const project = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.projectContext, projectImplementationContextV1Schema); const proposal = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.proposal, proposedFileChangesSchema); const approval = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.approval, implementationApprovalBindingSchema); const snapshot = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.snapshot, z.unknown()) as ProjectSnapshot; const current = inspectRegisteredProject(requested.project); if (approval.proposalArtifactId !== IMPLEMENTATION_ARTIFACT_IDS.proposal || approval.proposalHash !== proposalHash(proposal) || approval.projectId !== proposal.projectId || approval.baseProjectFingerprint !== proposal.baseProjectFingerprint) throw new DesignFlowError("ERR_APPROVAL_MISMATCH", "Approval no longer matches the proposed implementation."); if (current.project.contextFingerprint !== proposal.baseProjectFingerprint) throw new Error("The project changed after the proposal was created. Generate a new proposal before continuing."); const result = await applyProjectFileChanges(project.project.id, requested.project.rootPath, proposal, project.project.rootIdentity, requested.stateDirectory, snapshot); return writeArtifact(context, { artifactId: IMPLEMENTATION_ARTIFACT_IDS.application, artifactType: IMPLEMENTATION_ARTIFACT_TYPES.application, name: "File application result", payload: result, summary: { runId: result.runId, changedFiles: result.changedFiles } }); } };

export const validateImplementationCapability: Capability<unknown, CapabilityOutput> = { id: "run-project-validation", name: "Run project validation", description: "Runs only discovered project checks and rolls back required failures", type: "write_fs", version: "1", inputSchema: inputSchema, outputSchema: capabilityOutputSchema, async execute(context, input) { const requested = projectInput(input); const project = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.projectContext, projectImplementationContextV1Schema); const application = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.application, z.object({ runId: z.string(), projectId: z.string(), proposalHash: z.string(), changedFiles: z.array(z.string()), createdFiles: z.array(z.string()), modifiedFiles: z.array(z.string()), snapshot: z.unknown() }).passthrough()); const checks = await validateProject(project, requested.project.rootPath, { signal: context.signal }); const failed = checks.some((check) => check.required && check.status !== "passed"); let rollbackTriggered = false; if (failed) { rollbackTriggered = true; await rollbackProjectSnapshot(requested.project.rootPath, application.snapshot as Parameters<typeof rollbackProjectSnapshot>[1]); } const report = implementationValidationReportSchema.parse({ schemaVersion: "1", projectId: project.project.id, proposalArtifactId: IMPLEMENTATION_ARTIFACT_IDS.proposal, applicationArtifactId: IMPLEMENTATION_ARTIFACT_IDS.application, checks, passed: !failed, rollbackTriggered, ...(rollbackTriggered ? { rollbackArtifactId: `${application.runId}-rollback` } : {}), warnings: failed ? ["A required project check failed; the project was restored."] : [] }); return writeArtifact(context, { artifactId: IMPLEMENTATION_ARTIFACT_IDS.validation, artifactType: IMPLEMENTATION_ARTIFACT_TYPES.validation, name: "Implementation validation", payload: report, summary: { passed: report.passed, rollbackTriggered: report.rollbackTriggered } }); } };

/**
 * The provenance this step must be told rather than assume.
 *
 * The generated-implementation record used to spell out an agent version and a
 * model profile as literals, which meant it reported the same two values no
 * matter which agent version or profile actually ran. The node now maps the
 * workflow's own inputs in, so the record describes the run that produced it.
 *
 * Nothing downstream hashes this payload: approval binds to the proposal
 * (`proposalHash`), the correction loop binds to the inspected project
 * (`currentImplementationHash`) and to the visual report, and `objectHash` is
 * never applied to a generated-implementation. Changing these two fields
 * therefore changes what is reported, not what is enforced.
 */
const generatedProvenanceInputSchema = z.object({ implementationAgentVersion: z.string().min(1), implementationAgentModelProfileId: z.string().min(1).default("implementation-default") });

export const storeGeneratedImplementationCapability: Capability<unknown, CapabilityOutput> = { id: "store-generated-implementation", name: "Store generated implementation", description: "Records the approved application and validation lineage", type: "pure", version: "1", inputSchema: generatedProvenanceInputSchema, outputSchema: capabilityOutputSchema, async execute(context, input) { const provenance = generatedProvenanceInputSchema.parse(input); const project = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.projectContext, projectImplementationContextV1Schema); const proposal = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.proposal, proposedFileChangesSchema); const validation = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.validation, implementationValidationReportSchema); if (!validation.passed) throw new DesignFlowError("ERR_REQUIRED_VALIDATION_FAILED", "Implementation validation failed; the project was restored.", { projectId: project.project.id }); const payload = { schemaVersion: "1", projectId: project.project.id, designSpecificationArtifactId: "design-specification", projectContextArtifactId: IMPLEMENTATION_ARTIFACT_IDS.projectContext, mappingArtifactId: IMPLEMENTATION_ARTIFACT_IDS.mapping, implementationPlanArtifactId: IMPLEMENTATION_ARTIFACT_IDS.plan, proposalArtifactId: IMPLEMENTATION_ARTIFACT_IDS.proposal, applicationArtifactId: IMPLEMENTATION_ARTIFACT_IDS.application, validationArtifactId: IMPLEMENTATION_ARTIFACT_IDS.validation, changedFiles: proposal.files.map((file) => file.path), createdFiles: proposal.files.filter((file) => file.action === "create").map((file) => file.path), modifiedFiles: proposal.files.filter((file) => file.action === "modify").map((file) => file.path), dependencyChanges: proposal.packageChanges.map((change) => change.packageName), reusedComponents: [], reusedTokens: [], assumptions: proposal.assumptions, unresolvedItems: proposal.unresolvedItems, agentId: "implementation-agent", agentVersion: provenance.implementationAgentVersion, modelProfileId: provenance.implementationAgentModelProfileId }; return writeArtifact(context, { artifactId: IMPLEMENTATION_ARTIFACT_IDS.generated, artifactType: IMPLEMENTATION_ARTIFACT_TYPES.generated, name: "Generated implementation", payload, summary: { projectId: payload.projectId, passed: validation.passed, changedFiles: payload.changedFiles } }); } };

export const storeStage4SummaryCapability: Capability<unknown, CapabilityOutput> = { id: "store-stage-4-summary", name: "Store Stage 4 summary", description: "Summarizes proposal, application, validation, and rollback state", type: "pure", version: "1", inputSchema: z.unknown(), outputSchema: capabilityOutputSchema, async execute(context) { const validation = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.validation, implementationValidationReportSchema); return writeArtifact(context, { artifactId: IMPLEMENTATION_ARTIFACT_IDS.summary, artifactType: IMPLEMENTATION_ARTIFACT_TYPES.summary, name: "Stage 4 summary", payload: { schemaVersion: "1", projectId: validation.projectId, proposalArtifactId: validation.proposalArtifactId, validationArtifactId: validationArtifactId(), passed: validation.passed, rollbackTriggered: validation.rollbackTriggered, visualComparisonPerformed: false }, summary: { passed: validation.passed, rollbackTriggered: validation.rollbackTriggered } }); } };
function validationArtifactId(): string { return IMPLEMENTATION_ARTIFACT_IDS.validation; }

export const implementationSideEffectCapabilities: readonly Capability<unknown, CapabilityOutput>[] = [storeImplementationApprovalCapability, createProjectSnapshotCapability, applyApprovedFileChangesCapability, validateImplementationCapability, storeGeneratedImplementationCapability, storeStage4SummaryCapability];
