import type { WorkflowDefinition } from "@designflow/sdk";
export const designToCodeImplementationWorkflow: WorkflowDefinition = { id: "design-to-code-implementation", name: "Design → Code (Implementation)", description: "Experimental Figma-backed implementation proposal workflow for a registered project", nodes: [
  { id: "parse-figma-source", capabilityId: "parse-figma-source", inputMap: { designFile: { $workflowInput: "designFile" }, frames: { $workflowInput: "frames" }, allowFixtureNames: { $workflowInput: "allowFixtureNames" } }, produces: ["parsed-figma-source"], next: ["retrieve-figma-source-snapshot"] },
  { id: "retrieve-figma-source-snapshot", capabilityId: "retrieve-figma-source-snapshot", inputMap: { captureScreenshots: { $workflowInput: "captureScreenshots" }, refreshFigmaSource: { $workflowInput: "refreshFigmaSource" } }, produces: ["figma-source-snapshot"], execution: { dependsOn: ["parse-figma-source"] }, next: ["invoke-figma-specification-agent"] },
  { id: "invoke-figma-specification-agent", capabilityId: "invoke-figma-specification-agent", inputMap: { agentVersion: { $workflowInput: "figmaAgentVersion" }, modelProfileId: { $workflowInput: "figmaAgentModelProfileId" } }, produces: ["design-specification"], execution: { dependsOn: ["retrieve-figma-source-snapshot"] }, next: ["inspect-registered-project"] },
  { id: "inspect-registered-project", capabilityId: "inspect-registered-project", inputMap: { enabled: { $workflowInput: "enabled" }, designFile: { $workflowInput: "designFile" }, frames: { $workflowInput: "frames" }, project: { $workflowInput: "project" }, stateDirectory: { $workflowInput: "stateDirectory" }, figmaAgentVersion: { $workflowInput: "figmaAgentVersion" }, implementationAgentVersion: { $workflowInput: "implementationAgentVersion" }, implementationAgentModelProfileId: { $workflowInput: "implementationAgentModelProfileId" } }, produces: ["project-implementation-context"], execution: { dependsOn: ["invoke-figma-specification-agent"] }, next: ["map-design-system"] },
  { id: "map-design-system", capabilityId: "map-design-system", inputMap: {}, produces: ["design-system-mapping"], execution: { dependsOn: ["inspect-registered-project", "invoke-figma-specification-agent"] }, next: ["invoke-implementation-agent"] },
  { id: "invoke-implementation-agent", capabilityId: "invoke-implementation-agent", inputMap: { agentVersion: { $workflowInput: "implementationAgentVersion" }, modelProfileId: { $workflowInput: "implementationAgentModelProfileId" } }, produces: ["implementation-agent-output"], execution: { dependsOn: ["map-design-system"] }, next: ["store-implementation-plan"] },
  { id: "store-implementation-plan", capabilityId: "store-implementation-plan", inputMap: { agentVersion: { $workflowInput: "implementationAgentVersion" }, modelProfileId: { $workflowInput: "implementationAgentModelProfileId" } }, produces: ["implementation-plan"], execution: { dependsOn: ["invoke-implementation-agent"] }, next: ["store-proposed-file-changes"] },
  { id: "store-proposed-file-changes", capabilityId: "store-proposed-file-changes", inputMap: {}, produces: ["proposed-file-changes"], execution: { dependsOn: ["store-implementation-plan"] }, next: ["request-implementation-approval"] },
  { id: "request-implementation-approval", capabilityId: "request-implementation-approval", inputMap: {}, produces: ["implementation-approval"], execution: { dependsOn: ["store-proposed-file-changes"] }, next: ["create-project-snapshot"] },
  { id: "create-project-snapshot", capabilityId: "create-project-snapshot", inputMap: { enabled: { $workflowInput: "enabled" }, designFile: { $workflowInput: "designFile" }, frames: { $workflowInput: "frames" }, project: { $workflowInput: "project" }, stateDirectory: { $workflowInput: "stateDirectory" }, figmaAgentVersion: { $workflowInput: "figmaAgentVersion" }, implementationAgentVersion: { $workflowInput: "implementationAgentVersion" }, implementationAgentModelProfileId: { $workflowInput: "implementationAgentModelProfileId" } }, produces: ["project-snapshot"], execution: { dependsOn: ["request-implementation-approval"] }, next: ["apply-approved-file-changes"] },
  { id: "apply-approved-file-changes", capabilityId: "apply-approved-file-changes", inputMap: { enabled: { $workflowInput: "enabled" }, designFile: { $workflowInput: "designFile" }, frames: { $workflowInput: "frames" }, project: { $workflowInput: "project" }, stateDirectory: { $workflowInput: "stateDirectory" }, figmaAgentVersion: { $workflowInput: "figmaAgentVersion" }, implementationAgentVersion: { $workflowInput: "implementationAgentVersion" }, implementationAgentModelProfileId: { $workflowInput: "implementationAgentModelProfileId" } }, produces: ["file-application-result"], execution: { dependsOn: ["create-project-snapshot"] }, next: ["run-project-validation"] },
  { id: "run-project-validation", capabilityId: "run-project-validation", inputMap: { enabled: { $workflowInput: "enabled" }, designFile: { $workflowInput: "designFile" }, frames: { $workflowInput: "frames" }, project: { $workflowInput: "project" }, stateDirectory: { $workflowInput: "stateDirectory" }, figmaAgentVersion: { $workflowInput: "figmaAgentVersion" }, implementationAgentVersion: { $workflowInput: "implementationAgentVersion" }, implementationAgentModelProfileId: { $workflowInput: "implementationAgentModelProfileId" } }, produces: ["implementation-validation"], execution: { dependsOn: ["apply-approved-file-changes"] }, next: ["store-generated-implementation"] },
  { id: "store-generated-implementation", capabilityId: "store-generated-implementation", inputMap: {}, produces: ["generated-implementation"], execution: { dependsOn: ["run-project-validation"] }, next: ["store-stage-4-summary"] },
  { id: "store-stage-4-summary", capabilityId: "store-stage-4-summary", inputMap: {}, produces: ["stage-4-summary"], execution: { dependsOn: ["store-generated-implementation"] }, next: [] },
], metadata: { version: "0.1.0", author: "DesignFlow Team", tags: ["design", "figma", "implementation", "stage-4", "experimental"] } };
