import { z } from "zod";
import { designSpecificationSchema, generatedImplementationSchema, type Capability, implementationPlanV1Schema, proposedFileChangesSchema } from "@designflow/sdk";
import { inspectRegisteredProject, mapDesignSystem, projectFileHash, validateProposedFileChanges } from "@designflow/capability-implementation";
import { join } from "node:path";
import { readArtifact, writeArtifact } from "./artifact-io";
import { capabilityOutputSchema, type CapabilityOutput } from "./types";
import { IMPLEMENTATION_ARTIFACT_IDS, IMPLEMENTATION_ARTIFACT_TYPES, implementationWorkflowInputSchema, projectImplementationContextV1Schema, designSystemMappingSchema } from "./implementation-types";
function requireAgents(context: import("@designflow/sdk").CapabilityContext): NonNullable<import("@designflow/sdk").CapabilityContext["agents"]> { if (!context.agents) throw new Error("Implementation Agent invocation is unavailable."); return context.agents; }

export const inspectRegisteredProjectCapability: Capability<unknown, CapabilityOutput> = { id: "inspect-registered-project", name: "Inspect registered project", description: "Builds a bounded implementation context from a registered project", type: "pure", version: "1", inputSchema: implementationWorkflowInputSchema, outputSchema: capabilityOutputSchema, async execute(context, input) { const requested = implementationWorkflowInputSchema.parse(input); const value = inspectRegisteredProject(requested.project, undefined, context.signal); return writeArtifact(context, { artifactId: IMPLEMENTATION_ARTIFACT_IDS.projectContext, artifactType: IMPLEMENTATION_ARTIFACT_TYPES.projectContext, name: "Project Implementation Context", payload: value, summary: { projectId: value.project.id, fingerprint: value.project.contextFingerprint, warningCount: value.warnings.length } }); } };
export const mapDesignSystemCapability: Capability<unknown, CapabilityOutput> = { id: "map-design-system", name: "Map design system", description: "Maps design tokens and components to bounded project facts", type: "pure", version: "1", inputSchema: z.unknown(), outputSchema: capabilityOutputSchema, async execute(context) { const spec = await readArtifact(context, "design-specification", designSpecificationSchema); const project = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.projectContext, projectImplementationContextV1Schema); const value = mapDesignSystem(spec, project); return writeArtifact(context, { artifactId: IMPLEMENTATION_ARTIFACT_IDS.mapping, artifactType: IMPLEMENTATION_ARTIFACT_TYPES.mapping, name: "Design System Mapping", payload: value, summary: { unresolved: value.unresolved.length } }); } };
export const invokeImplementationAgentStage4Capability: Capability<unknown, CapabilityOutput> = { id: "invoke-implementation-agent", name: "Invoke Implementation Agent", description: "Produces a schema-validated implementation output from bounded context", type: "pure", version: "1", inputSchema: z.object({ agentVersion: z.string().min(1), modelProfileId: z.string().min(1) }).strict(), outputSchema: capabilityOutputSchema, async execute(context, input) { const requested = z.object({ agentVersion: z.string().min(1), modelProfileId: z.string().min(1) }).parse(input); const spec = await readArtifact(context, "design-specification", designSpecificationSchema); const project = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.projectContext, projectImplementationContextV1Schema); const mapping = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.mapping, designSystemMappingSchema); const outcome = await requireAgents(context).invoke({ agentId: "implementation-agent", objective: "Produce a structured implementation proposal for the registered project", input: { designSpecification: spec, projectContext: project, designSystemMapping: mapping }, attempt: 1 }, context.signal); if (outcome.type === "failure") throw new Error(`Implementation Agent failed: ${outcome.code}`); const value = generatedImplementationSchema.parse(outcome.output); return writeArtifact(context, { artifactId: IMPLEMENTATION_ARTIFACT_IDS.agentOutput, artifactType: IMPLEMENTATION_ARTIFACT_TYPES.agentOutput, name: "Implementation Agent output", payload: value, summary: { agentVersion: requested.agentVersion, modelProfileId: requested.modelProfileId, fileCount: value.files.length } }); } };
export const createImplementationPlanCapability: Capability<unknown, CapabilityOutput> = { id: "store-implementation-plan", name: "Store implementation plan", description: "Creates a structured implementation plan from specification, mapping, and agent output", type: "pure", version: "1", inputSchema: z.object({ agentVersion: z.string().min(1), modelProfileId: z.string().min(1) }).strict(), outputSchema: capabilityOutputSchema, async execute(context, input) { const requested = z.object({ agentVersion: z.string().min(1), modelProfileId: z.string().min(1) }).parse(input); const spec = await readArtifact(context, "design-specification", designSpecificationSchema); const mapping = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.mapping, designSystemMappingSchema); const project = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.projectContext, projectImplementationContextV1Schema); const agentOutput = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.agentOutput, generatedImplementationSchema); const plan = implementationPlanV1Schema.parse({ schemaVersion: "1", objective: `Implement ${spec.frames.join(", ") || "the selected design"} in the registered project.`, selectedNodeIds: spec.hierarchy.map((node) => node.id), targetRoute: project.structure.routeRoots[0], reuseComponents: mapping.componentMappings.filter((m) => m.action === "reuse").map((m) => m.projectComponentReference!), extendComponents: mapping.componentMappings.filter((m) => m.action === "extend").map((m) => m.projectComponentReference!), createComponents: agentOutput.files.filter((file) => file.action === "create").map((file) => file.path), reuseTokens: mapping.tokenMappings.filter((m) => m.action === "reuse").map((m) => m.projectTokenReference!), addTokens: mapping.tokenMappings.filter((m) => m.action === "create").map((m) => m.designTokenId), assets: spec.assets.map((a) => a.id), statePlan: spec.states, responsivePlan: spec.responsiveAssumptions, accessibilityPlan: spec.accessibilityNotes, proposedFileActions: agentOutput.files.map((file) => ({ path: file.path, action: file.action })), dependencyChanges: [], validationPlan: Object.keys(project.commands), assumptions: [...spec.ambiguities.map((a) => a.description), ...agentOutput.assumptions], unresolvedQuestions: [...mapping.unresolved.map((u) => u.description), ...agentOutput.unresolvedItems], agent: { id: "implementation-agent", version: requested.agentVersion, modelProfileId: requested.modelProfileId, schemaVersion: "1" } }); return writeArtifact(context, { artifactId: IMPLEMENTATION_ARTIFACT_IDS.plan, artifactType: IMPLEMENTATION_ARTIFACT_TYPES.plan, name: "Implementation Plan", payload: plan, summary: { componentCount: plan.createComponents.length + plan.reuseComponents.length } }); } };
export const createProposalCapability: Capability<unknown, CapabilityOutput> = { id: "store-proposed-file-changes", name: "Store proposed file changes", description: "Stores bounded, reviewable file proposals without writing files", type: "pure", version: "1", inputSchema: implementationWorkflowInputSchema, outputSchema: capabilityOutputSchema, async execute(context, input) { const requested = implementationWorkflowInputSchema.parse(input); const project = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.projectContext, projectImplementationContextV1Schema); const plan = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.plan, implementationPlanV1Schema); const agentOutput = await readArtifact(context, IMPLEMENTATION_ARTIFACT_IDS.agentOutput, generatedImplementationSchema); const outputByPath = new Map(agentOutput.files.map((file) => [file.path, file])); const root = requested.project.rootPath; if (root === undefined) throw new Error("A registered project root is required to validate the proposal."); const proposal = proposedFileChangesSchema.parse({ schemaVersion: "1", projectId: project.project.id, baseProjectFingerprint: project.project.contextFingerprint, files: plan.proposedFileActions.map((action) => { const file = outputByPath.get(action.path); const baseHash = action.action === "modify" ? projectFileHash(join(root, action.path)) : undefined; return { path: action.path, action: action.action, content: file?.content, ...(baseHash !== undefined ? { expectedBaseHash: baseHash } : {}), reason: file?.reason ?? "Implementation Agent proposal.", relatedDesignNodeIds: plan.selectedNodeIds }; }), packageChanges: [], commandsRequested: Object.values(project.commands).filter(Boolean).map((command) => ({ name: command!.name, required: command!.required })), assumptions: plan.assumptions, unresolvedItems: plan.unresolvedQuestions }); // Deterministic host validation BEFORE the approval prompt: operation
    // semantics (modify/delete target must exist, create must not), path
    // safety, and size bounds. An invalid proposal fails here with a typed
    // error instead of being presented for approval.
    validateProposedFileChanges(proposal, root); return writeArtifact(context, { artifactId: IMPLEMENTATION_ARTIFACT_IDS.proposal, artifactType: IMPLEMENTATION_ARTIFACT_TYPES.proposal, name: "Proposed File Changes", payload: proposal, summary: { createCount: proposal.files.filter((f) => f.action === "create").length, modifyCount: proposal.files.filter((f) => f.action === "modify").length } }); } };
export const implementationCapabilities: readonly Capability<unknown, CapabilityOutput>[] = [inspectRegisteredProjectCapability, mapDesignSystemCapability, invokeImplementationAgentStage4Capability, createImplementationPlanCapability, createProposalCapability];
