import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { createFigmaSpecificationHost, SAMPLE_FIGMA_MCP_FIXTURES, type FigmaSpecificationHost } from "./harness.test-support";
import { designToCodeImplementationApprovalPolicy } from "./implementation-manifest";
import { IMPLEMENTATION_ARTIFACT_IDS } from "./implementation-types";

const hosts: FigmaSpecificationHost[] = [];
afterEach(async () => { for (const host of hosts.splice(0)) host.close(); });

async function fixture(failValidation = false): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "designflow-stage4-workflow-"));
  const sentinel = ["must-never-leak", "7f82c"].join("-");
  await writeFile(join(root, "package.json"), JSON.stringify({ name: "stage4-fixture", scripts: { typecheck: failValidation ? "bun run missing-check" : "bun --version", build: "bun --version" }, dependencies: { react: "18.0.0" } }));
  await writeFile(join(root, "package-lock.json"), "{}\n");
  await writeFile(join(root, ".env"), `DESIGNFLOW_TEST_SECRET=${sentinel}\n`);
  await writeFile(join(root, "src-placeholder"), "fixture\n");
  return root;
}

function input(root: string, stateDirectory: string) {
  return { enabled: true as const, designFile: "https://www.figma.com/design/E958ARSSBoJjblLhxZQVSU/Spendly?node-id=432-2906&t=YkNcoLPyhLHx58O9-1", frames: ["Header"], project: { id: "fixture-project", name: "Stage 4 Fixture", rootPath: root }, stateDirectory, captureScreenshots: false, refreshFigmaSource: false, allowFixtureNames: false, figmaAgentVersion: "0.1.0", implementationAgentVersion: "0.1.0", implementationAgentModelProfileId: "implementation-default" };
}

describe("Stage 4 implementation workflow", () => {
  test("runs through specification, inspection, mapping, proposal, approval, application and validation", async () => {
    const root = await fixture();
    const state = await mkdtemp(join(tmpdir(), "designflow-stage4-state-"));
    const host = await createFigmaSpecificationHost({ fixtures: SAMPLE_FIGMA_MCP_FIXTURES, policy: designToCodeImplementationApprovalPolicy, implementation: true });
    hosts.push(host);
    const handle = await host.runner.start({ workflowId: "design-to-code-implementation", input: input(root, state) });
    expect(handle.state).toBe("needs_approval");
    expect(await readFile(join(root, ".env"), "utf8")).toContain(["must-never-leak", "7f82c"].join("-"));
    expect(await host.artifactStore.getArtifact(IMPLEMENTATION_ARTIFACT_IDS.proposal)).not.toBeNull();
    expect(await host.artifactStore.getArtifact(IMPLEMENTATION_ARTIFACT_IDS.snapshot)).toBeNull();
    expect(await host.artifactStore.getArtifact(IMPLEMENTATION_ARTIFACT_IDS.application)).toBeNull();
    expect(await host.artifactStore.getArtifact(IMPLEMENTATION_ARTIFACT_IDS.validation)).toBeNull();
    expect((await host.service.resume("design-to-code-implementation")).status).toBe("pending_approval");
    const rejected = await host.runner.reject(handle.executionId, "Rejecting preview leaves the fixture untouched.");
    expect(rejected.state).toBe("failed");
    await expect(readFile(join(root, "src/Header.tsx"))).rejects.toBeDefined();
    await rm(root, { recursive: true, force: true });
    await rm(state, { recursive: true, force: true });
  });

  test("approved changes produce final lineage and a successful validation report", async () => {
    const root = await fixture();
    const state = await mkdtemp(join(tmpdir(), "designflow-stage4-state-"));
    const host = await createFigmaSpecificationHost({ fixtures: SAMPLE_FIGMA_MCP_FIXTURES, policy: designToCodeImplementationApprovalPolicy, implementation: true });
    hosts.push(host);
    const handle = await host.runner.start({ workflowId: "design-to-code-implementation", input: input(root, state) });
    expect(handle.state).toBe("needs_approval");
    const approved = await host.runner.approve(handle.executionId, "Approved exact proposal for the registered fixture.");
    expect(approved.state).toBe("ready");
    await expect(host.runner.approve(handle.executionId, "duplicate")).rejects.toBeDefined();
    expect(await host.artifactStore.getArtifact(IMPLEMENTATION_ARTIFACT_IDS.snapshot)).not.toBeNull();
    expect(await host.artifactStore.getArtifact(IMPLEMENTATION_ARTIFACT_IDS.generated)).not.toBeNull();
    const summary = await host.artifactStore.getArtifact(IMPLEMENTATION_ARTIFACT_IDS.summary);
    expect(summary).not.toBeNull();
    expect(await readFile(join(root, "src/Header.tsx"), "utf8")).toContain("Generated by the Implementation Agent");
    await rm(root, { recursive: true, force: true });
    await rm(state, { recursive: true, force: true });
  });

  test("required validation failure rolls the fixture back automatically", async () => {
    const root = await fixture(true);
    const state = await mkdtemp(join(tmpdir(), "designflow-stage4-state-"));
    const host = await createFigmaSpecificationHost({ fixtures: SAMPLE_FIGMA_MCP_FIXTURES, policy: designToCodeImplementationApprovalPolicy, implementation: true });
    hosts.push(host);
    const handle = await host.runner.start({ workflowId: "design-to-code-implementation", input: input(root, state) });
    expect(handle.state).toBe("needs_approval");
    const result = await host.runner.approve(handle.executionId, "Approve controlled validation failure.");
    expect(result.state).toBe("failed");
    const validation = await host.artifactStore.getArtifact(IMPLEMENTATION_ARTIFACT_IDS.validation);
    expect(validation).not.toBeNull();
    await expect(readFile(join(root, "src/Header.tsx"))).rejects.toBeDefined();
    await rm(root, { recursive: true, force: true });
    await rm(state, { recursive: true, force: true });
  });
});
